# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/betting_rl_env/',
                'doc_host': 'https://{user}.github.io',
                'git_url': 'https://github.com/{user}/betting_rl_env/',
                'lib_path': 'betting_rl_env'},
  'syms': {'betting_rl_env.betting_env': {}}}